spring.application.name=NyanID
#spring.mvc.apiversion.use.header=Api-Version
spring.config.location=classpath:config/*
spring.web.error.path=/error
spring.mvc.static-path-pattern=/**.ico
spring.web.resources.static-locations=classpath:/
logging.pattern.console=[%clr(%d{yyyy-MM-dd HH:mm:ss})] [%clr(%5p)] %clr(-){cyan} %msg%n
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false
spring.web.error.whitelabel.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.mail.properties.ssl.trust-all-certs=true
spring.datasource.hikari.max-lifetime=55000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.leak-detection-threshold=5000
spring.jpa.properties.hibernate.transaction.jta.platform=none
#server.undertow.io-threads=6
#server.undertow.worker-threads=80
#server.undertow.buffer-size=1024
#server.undertow.direct-buffers=true

